<?php include '../integrations/part/navbar.part.php'; ?>

    <section id="middle-section">

        <div class="title-message">
        <i class="far fa-user icon-user"></i>
        <h1>Modifier un cours<br>
            "L'enseignement est l'une des clés de la réussite"</h1>
        </div>

        <?php if (!empty($ERRORS)) : ?>
            <div class="error">
                <ul>
                <?php foreach ($ERRORS as $error) : ?>
                    <li><?= $error; ?></li>
                <?php endforeach; ?>
                </ul>
            </div>
        <?php endif; ?>
    
        <form id="form-inscription" method="POST" action="modifierCour.php">
            <div class="form-inscription-one">
                    <input type="text" name="titre" id="titre" value="<?= isset($titre) ? $titre : $cour['titre']; ?>"autofocus>

                    <input type="datetime" name="dateDebut" id="dateDebut" value="<?= isset($dateDebut) ? $dateDebut : $cour['dateDebut']; ?>">  

                    <input type="datetime" name="dateFin" id="dateFin" value="<?= isset($dateFin) ? $dateFin : $cour['dateFin']; ?>">  

            </div>
            <div class="form-inscription-two">
                    <select name="idClasse">
                        <?php foreach($classes as $classe) : ?>
                        <option <?= ($classe['idClasse'] == $classe['idClasse'] ? 'selected' : ''); ?> value="<?=$classe['idClasse'];?>"><?= $classe['nom']; ?>
                        </option>
                        <?php endforeach; ?>  
                    </select>

                    <select name="etat">
                        <option value="ouvert">ouvert</option>  
                        <option value="ferme">ferme</option>
                    </select>

                <input type="hidden" name="idCours" value="<?= isset($idCour) ? $idCour : $cour['idCours']; ?>" />
                <button class="button button-success" type="submit">Modifier</button> 
            </div>
        </form>
    </section>    

