<?php include '../integrations/part/navbar.part.php'; ?>

    <section id="middle-section">

        <div class="title-message">
        <i class="far fa-user icon-user"></i>
        <h1>Ajouter un cours<br>
            "L'enseignement est l'une des clés de la réussite"</h1>
        </div class="error">

        <?php if (!empty($ERRORS)) : ?>
            <div class="error">
                <ul>
                <?php foreach ($ERRORS as $error) : ?>
                    <li><?= $error; ?></li>
                <?php endforeach; ?>
                </ul>
            </div>
        <?php endif; ?>
    
        <form id="form-inscription" method="POST" action="formulaireAjoutCour.php">

            <div class="form-inscription-one">
                    <input type="text" name="titre" placeholder="Nom du cours" autofocus >

                    <input type="datetime-local" name="dateDebut" id="dateDebut" placeholder="Date de Début" value="<?= isset($dateDebut) ? $dateDebut : ''; ?>">
                    
                    <input type="datetime-local" name="dateFin" id="dateFin" placeholder="Date de fin" value="<?= isset($dateFin) ? $dateFin : ''; ?>">
            </div>

            <div class="form-inscription-two">
                    <select name="idClasse">
                        <?php foreach($classes as $classe) : ?>
                        <option value="<?=$classe['idClasse'];?>"><?= $classe['nom']; ?>
                        </option>
                        <?php endforeach; ?>  
                    </select>

                    <select name="etat">
                        <option value="ouvert">ouvert</option>  
                        <option value="ferme">ferme</option>
                    </select>

                <input type="hidden" name="idCour" value="<?= isset($idCour) ? $idCour : $Cour['idCour']; ?>" />
                <button class="button button-success" type="submit">Enregistrer</button>
            </div>
        </form>
    </section>    

