<?php include '../integrations/part/navbar.part.php'; ?>
    
    <section id="middle-section">
    
        <div class="title-message">
            <i class="far fa-user icon-user"></i>
            <h1>Liste des Cours<br>
            "L'enseignement est l'une des clés de la réussite"</h1>
        </div>

        <form id="form-list" method="POST" action="listeDesCours.php">
            <p id="search-btn">  
            <input type="text" placeholder="Entrer un nom">
            <button class="button button-success">Rechercher</button>
            </p>

            <div id="add-btn">
                <a class="button button-info" href="formulaireAjoutCour.php">Ajouter</a>
            </div>
            <table id="user_list">
                <tr>
                    <th>Titre</th>
                    <th>Date de Début</th>
                    <th>Date de Fin</th>
                    <th>Classe</th>
                    <th>Etat</th>
                    <th>Actions</th>
                    </tr>
                        <?php foreach($cours as $cour) : ?>
                    <tr>
                
                    <td><?= $cour['titre']; ?></td>
                    <td><?= strftime("%d %b %Y à %H:%M",strtotime($cour['dateDebut'])); ?></td>
                    <td><?= strftime("%d %b %Y à %H:%M",strtotime($cour['dateFin'])); ?></td>
                    <td><?= $cour['idClasse']; ?></td>
                    <td><?= $cour['etat']; ?></td>
                    
                    <td>
                    <div class="user_list_btn">
                        <a class="button button-info" href="formulaireCour.php?id=<?= $cour['idCours']; ?>">Modifier</a>
                        <a class="button button-danger" href="supprimerCour.php?id=<?= $cour['idCours']; ?>">Supprimer</a>
                    </div>
                    </td>
                </tr>
                <?php endforeach; ?>
                
            </table>
        </form>  
    </section>

                <script>

                    $(document).ready(function() {
                        $('.button-danger').on('click', function(event){
                            event.preventDefault();
                            if(confirm('Voulez vous vraiment supprimer ce cours ?') == true){
                                window.location.href = $(this).attr('href');
                            }
                        });
                    });



                /* $(document).ready(function() {
                        $('.button-info').on('click', function(event){
                            event.preventDefault();
                            let id = $('#user_selected').val();
                            window.location.href = "modifierUtilisateur.php?id="+id;
                        });
                    }); */
                </script>