<?php include '../integrations/part/navbar.part.php'; ?>

    <section id="middle-section">

        <div class="title-message">
            <i class="far fa-user icon-user"></i>
            <h1>Supprimer un cours<br>
                "L'enseignement est l'une des clés de la réussite"</h1>
        </div>
        <div class="message-delete">
            <i class="fas fa-exclamation-triangle"></i>
            <p class="info-suppression"><span>Vous êtes sur le point de supprimer le cours "HTML".</span><br>
            Êtes-vous sûr de vouloir supprimer ce cours ?
            <div class="delete-btn">
                <button class="button button-danger">Supprimer</button>
                <button class="button button-info">Annuler</button>
            </div>
            </p>
        </div>

    </section>