
    <section id="top-section-header-and-title">
        <header>
            <img src="../integrations/res/img/logo.png" alt="logo">
            <nav>
                <ul>
                    <li>
                        <button type="button">
                            <i class="fas fa-chalkboard-teacher"></i>
                            <a href="connexion.php" alt="" >Déconnexion</a>
                        </button>
                    </li>
                </ul>
            </nav>
        </header>
    </section>

    <section id="middle-section">

        <div class="title-message">
            <i class="far fa-user icon-user"></i>
            <h1>Supprimer un cours<br>
                "L'enseignement est l'une des clés de la réussite"</h1>
        </div>
        <div class="message-delete">
            <i class="fas fa-exclamation-triangle"></i>
            <p class="info-suppression"><span>Vous êtes sur le point de supprimer le cours "HTML".</span><br>
            Êtes-vous sûr de vouloir supprimer ce cours ?
            <div class="delete-btn">
                <button class="button button-danger">Supprimer</button>
                <button class="button button-info">Annuler</button>
            </div>
            </p>
        </div>

    </section>