
    <section id="top-section-header-and-title">
        <header>
            <img src="integrations/res/img/logo.png" alt="logo">
            <nav>
                <ul>
                    <li>
                        <button type="button">
                        <i class="fas fa-chalkboard-teacher"></i>
                        <a href="connexion.php" alt="" >Déconnexion</a>
                        </button>
                    </li>
                </ul>
            </nav>
        </header>
    </section>
    <section id="middle-section">
        <div class="title-message">
            <i class="far fa-user icon-user"></i>
            <h1>Bienvenue dans l'interface d'administration<br>
            "L'enseignement est l'une des clés de la réussite"</h1>
        </div>
        
    <form id="form">
        <p>
            <label>Accéder aux listes :</label>
            <select>
                <option value="">Liste des cours </option>
                <option value="">Liste des classes</option>
                <option value="">Liste des utilisateurs</option> 
            </select>
        </p>
        <div>
        <button class="button button-success" type="submit">Accéder</button>
        </div>
    </form>
</section>
