

<section id="top-section-header-and-title">

        <header>
            <img src="integrations/res/img/logo.png" alt="logo">

            <nav>
                <ul>
                    <li>
                        <button type="button">
                        <i class="fas fa-chalkboard-teacher"></i>
                        <a href="connexion.php">Déconnexion</a>
                        </button> 
                    </li>
                </ul>
            </nav>
        </header>
    </section>

    <section id="middle-section">

        <div class="title-message">
        <i class="far fa-user icon-user"></i>
        <h1>Bienvenue sur votre page d'accueil formateurs<br>
            "L'enseignement est l'une des clés de la réussite"</h1>
        </div>

        <div class="btn-home-teacher">
            <button class="button button-success" type="submit">
                <a href="coursFormateur.php">Accéder à vos cours</a></button>
            <button class="button button-success" type="submit">
                <a href="relevePresence.php">Accéder au relevé de présence</a></button>
        </div>
        
    </section>
 









    










