

<section id="top-section-header-and-title">

        <header>
            <img src="integrations/res/img/logo.png" alt="logo">

            <nav>
                <ul>
                    <li>
                        <button type="button">
                        <i class="fas fa-chalkboard-teacher"></i>
                        <a href="connexion.php">Déconnexion</a>
                        </button> 
                    </li>
                </ul>
            </nav>
        </header>
    </section>

    <section id="middle-section-home-teachers">

        <div>
        <i class="far fa-user icon-user"></i>
        <h1>Bienvenue sur la page sur votre page d'accueil<br>
            "L'enseignement est l'une des clés de la réussite"</h1>
        </div>
        <button id="button-home-teachers">
            <a href="#">Accéder à vos cours</a></button>
        <button id="button-home-teachers-two">
            <a href="#">Accéder au relevé de présence</a></button>
    </section>
 









    










