
    <section id="top-section-header-and-title">
        <header>
            <img src="integrations/res/img/logo.png" alt="logo">
            <nav>
                <ul>
                    <li>
                        <i class="fas fa-chalkboard-teacher"></i>
                        <a href="" alt="" >Liste des cours</a>
                    </li>
                    <li>
                        <i class="fas fa-chalkboard-teacher"></i>
                        <a href="" alt="" >Liste des classes</a>
                    </li>
                    <li>
                        <i class="far fa-address-card"></i>
                        <a href="" alt="" >Liste des utilisateurs</a>
                    </li>
                    <li>
                        <i class="fas fa-chalkboard-teacher"></i>
                        <a href="connexion.php" alt="" >Déconnexion</a>
                    </li>
                </ul>
            </nav>
        </header>
    </section>
    <div class="title-admin-accueil" >
        <h1>Bienvenue dans l'interface d'administration</h1>
    </div>
    <section id="section-admin-accueil">
        <div>
            <img src="" alt="">
            <h3><a href="">Accéder à la liste des cours</a></h3>
        </div>
        <div>
            <img src="" alt="">
            <h3><a href="">Accéder à la liste des cours</a></h3>
        </div>
        <div>
            <img src="" alt="">
            <h3><a href="">Accéder à la liste des cours</a></h3>
        </div>
    </section>

