
    <section id="top-section-header-and-title">
        <header>
            <img src="integrations/res/img/logo.png" alt="logo">
            <nav>
                <ul>
                    <li>
                        <button type="button">
                            <i class="fas fa-chalkboard-teacher"></i>
                            <a href="connexion.php" alt="" >Déconnexion</a>
                        </button>
                    </li>
                </ul>
            </nav>
        </header>
    </section>
    
    <div class="container-ajout-utilisateur">
        
        <div class="msg-ajout-utilisateur">
            <i class="far fa-user icon-user"></i>
            <h1>Ajouter un Utilisateur</h1>
        </div>
        <div id="select-ajout-utilisateur">
            <select>
                <option value="">Administrateur </option>
                <option value="">Etudiant</option>
                <option value="">Formateur</option> 
            </select>
        </div>
        <form id="form-ajout-utilisateur">
            <label for="">Ajouter un utilisateur : </label>
            <input type="text" placeholder="Antoine La">
            <button class="button button-success">Rechercher</button><br/>
        </form>
        <section id="section-users-ajouter-utilisateur">
            <label>Les utilisateurs déjà ajoutés : </label>
            <ul>
                <li>Aurélien Durand <button class="button button-danger">Supprimer</button></li>
                <li>Céline Bernard <button class="button button-danger">Supprimer</button></li>
                <li>Alain Marechal <button class="button button-danger">Supprimer</button></li>
                <li>Laure Da Silva <button class="button button-danger">Supprimer</button></li>
                <li>Etienne Boucher <button class="button button-danger">Supprimer</button></li>
                <li>Magalie Perret <button class="button button-danger">Supprimer</button></li>
                <li>Christelle Monget <button class="button button-danger">Supprimer</button></li>
            </ul>    
        </section>
        <div class="ajout-user-btn">
            <button class="button button-info" type="submit">Ajouter un utilisateur</button>
        </div>
    </div>
