
    <section id="top-section-header-and-title">
        <header>
            <img src="integrations/res/img/logo.png" alt="logo">
            <nav>
                <ul>
                    <li>
                        <button type="button">
                            <i class="fas fa-chalkboard-teacher"></i>
                            <a href="connexion.php" alt="" >Déconnexion</a>
                        </button>
                    </li>
                </ul>
            </nav>
        </header>
    </section>
    
    <div class="container-ajout-utilisateur">
        
        <div class="msg-ajout-utilisateur">
            <i class="far fa-user icon-user"></i>
            <h1>Ajouter un Utilisateur</h1>
        </div>
        <div id="select-ajout-utilisateur">
            <select>
                <option value="">Administrateur </option>
                <option value="">Etudiant</option>
                <option value="">Formateur</option> 
            </select>
        </div>
        <form id="form-ajout-utilisateur">
            <label for="">Ajouter un utilisateur : </label>
            <input type="text" placeholder="Antoine La">
            <button class="button button-success">Rechercher</button><br/>
        </form>
        <form id="section-users-ajouter-utilisateur" method="POST" action="ajoutUtilisateur.php">
            <label for="add-users">Les utilisateurs déjà ajoutés : </label>
            <input type="text" name="add-users" id="add-users" value="
            <?php foreach($utilisateurs as $utilisateur) : ?>">
                    <li><?= $utilisateur['prenom']; ?> <?= $utilisateur['nom']; ?> <button class="button button-info">Modifier</button><button class="button button-danger">Supprimer</button></li>
                <?php endforeach; ?>
</input>    
        </form>
        <div class="ajout-user-btn">
            <button class="button button-info" type="submit">Ajouter un utilisateur</button>
        </div>
    </div>
