
    <section id="top-section-header-and-title">
        <header>
            <img src="integrations/res/img/logo.png" alt="logo">
            <nav>
                <ul>
                    <li>
                        <button type="button">
                        <i class="fas fa-chalkboard-teacher"></i>
                        <a href="connexion.php" alt="" >Déconnexion</a>
                        </button>
                    </li>
                </ul>
            </nav>
        </header>
    </section>

    <section id="container-ajout-cours">

        <div class="msg-ajout-cours">
        <i class="far fa-user icon-user"></i>
        <h1>Ajouter un cours<br>
            "L'enseignement est l'une des clés de la réussite"</h1>
        </div>

        <?php if (!empty($ERRORS)) : ?>
            <div class="error">
                <ul>
                <?php foreach ($ERRORS as $error) : ?>
                    <li><?= $error; ?></li>
                <?php endforeach; ?>
                </ul>
            </div>
        <?php endif; ?>
        

        <div class="div-ajouter-cours">
            <form id="form-ajout-cours" method="POST" action="ajouterCours.php">
                <div class="champs-ajout-cours">
                <input type="text" placeholder="Nom du cours">
                </div>
                <div id="select-ajout-cours">
                    <select>
                        <?php foreach($cours as $cours) : ?>
                        <option value="<?=$cours['idCours'];?>"><?= $cours['titre']; ?>
                        </option>
                        <?php endforeach; ?>  
                    </select>
                </div>
            
                <section id="calandar-ajout-cours">
                    <div class="date-debut">
                        <label for="">Date de début :</label><br>
                        <input type="date">
                        <input type="time" value="09:30">
                    </div>
                    <div class="date-fin">
                        <label for="">Date de fin :</label><br>
                        <input type="date">
                        <input type="time" value="17:30">  
                    </div>
                </section>
                <button class="button button-success" type="submit">Ajouter un cours</button>
            </form>
        </div>
        
    </section>    

