
    <section id="top-section-header-and-title">
        <header>
            <img src="integrations/res/img/logo.png" alt="logo">
            <nav>
                <ul>
                    <li>
                        <button type="button">
                            <i class="fas fa-chalkboard-teacher"></i>
                            <a href="connexion.php" alt="" >Déconnexion</a>
                        </button>
                    </li>
                </ul>
            </nav>
        </header>
    </section>
    
    <div class="container-ajout-utilisateur">
        
        <div class="msg-ajout-utilisateur">
            <i class="far fa-user icon-user"></i>
            <h1>Ajouter un Utilisateur</h1>
        </div>
        
        <form id="form-ajout-utilisateur" method="POST" action="ajoutUtilisateur.php">
        <div id="select-ajout-utilisateur">
        
        <!--
        </div>
            <label for="add-user">Ajouter un utilisateur : </label>
            <input type="text" name="addUser" id="addUser" value="<?= isset($addUser) ? $addUser : ''; ?>">
            <br>
-->

            <form id="form-addUser" method="POST" action="ajoutUtilisateur.php">
            <p>
            <select name="role">
                <option value="administrateur">Administrateur</option>
                <option value="etudiant">Etudiant</option>
                <option value="formateur">Formateur</option> 
            </select>
            <select name="class" id="">
                <option>N/A</option>
            <?php foreach($classes as $classe) : ?>
                    <option value="<?=$classe['idClasse'];?>"><?= $classe['nom']; ?></option>
                <?php endforeach; ?>
            </select>
            </p>
            <p>
                <label for="name">Votre nom : </label>
                <input type="text" name="name" id="name" value="<?= isset($name) ? $name : ''; ?>">
            </p>
            <p>
                <label for="firstname">Votre prénom : </label>
                <input type="text" name="firstname" id="firstname" value="<?= isset($firstname) ? $firstname : ''; ?>">
            </p>
            <p>
                <label for="email">Votre email : </label>
                <input type="email" name="email" id="email" value="<?= isset($email) ? $email : ''; ?>">
            </p>
            <p>
                <label for="password">Votre mot de passe : </label>
                <input type="password" name="enterpassword" id="enterpassword" value="<?= isset($enterpassword) ? $enterpassword : ''; ?>">
            </p>
            <div>
            <button class="button button-info" type="submit">Ajouter un utilisateur</button>
        </form>
    </div>
