

<section id="top-section-header-and-title">

    <header>
        <img src="integrations/res/img/logo.png" alt="logo">

        <nav>
            <ul>
                <li>
                    <button type="button">
                    <i class="fas fa-chalkboard-teacher"></i>
                    <a href="index.php">Retour à l'accueil</a>
                    </button> 
                </li>
            </ul>
        </nav>
    </header>
</section>

<section id="middle-section-connection">

    <div>
    <i class="far fa-user icon-user"></i>
    <h1>Bienvenue sur votre page de connexion<br>
        "L'apprentissage est l'une des clés de la réussite"</h1>
    </div>

    <form id="form-connection" action="#">
        <p>
            <label for="email">Votre email : </label>
            <input type="email" id="email" required>
        </p>
        <p>
            <label for="motdepasse">Votre mot de passe : </label>
            <input type="password" id="motdepasse" required>
        </p>
        <div>
        <button id="button-connection" type="submit">
            <a href="#">Connexion</a></button>
        </div>
    </form>

    
</section>
