

<section id="top-section-header-and-title">

    <header>
        <img src="integrations/res/img/logo.png" alt="logo">

        <nav>
            <ul>
                <li>
                    <button type="button">
                    <i class="fas fa-chalkboard-teacher"></i>
                    <a href="index.php">Retour à l'accueil</a>
                    </button> 
                </li>
            </ul>
        </nav>
    </header>
</section>

<section id="middle-section">

    <div class="title-message">
    <i class="far fa-user icon-user"></i>
    <h1>Bienvenue sur votre page de connexion<br>
        "L'apprentissage est l'une des clés de la réussite"</h1>
    </div>

    <?php if (!empty($ERRORS)) : ?>
            <div class="error">
                <ul>
                <?php foreach ($ERRORS as $error) : ?>
                    <li><?= $error; ?></li>
                <?php endforeach; ?>
                </ul>
            </div>
        <?php endif; ?>

    <form id="form" action="connexion.php">
        <p>
            <label for="email">Votre email : </label>
            <input type="email" id="email" required>
        </p>
        <p>
            <label for="motdepasse">Votre mot de passe : </label>
            <input type="password" id="motdepasse" required>
        </p>
        <div>
        <button class="button button-success" type="submit">Connexion</button>
        </div>
    </form>

    
</section>
