

    <section id="top-section-header-and-title">

        <header>
            <img src="integrations/res/img/logo.png" alt="logo">

            <nav>
                <ul>
                    <li>
                        <button type="button">
                            <i class="fas fa-chalkboard-teacher"></i>
                            <a href="connexion.php">Déconnexion</a>
                        </button>
                    </li>
                </ul>
            </nav>
        </header>
    </section>

    <section id="middle-section-studies-students">

        <div id="time-studies-students">
            <p>30/03/20 09:03:23</p>
        </div>

        <div id="welcome-message">
            <i class="far fa-user icon-user"></i>
            <h1>Bienvenue sur la page de vos cours<br>
                "L'apprentissage est l'une des clés de la réussite"
            </h1>
        </div>

        <div id="lessons-student">
        <div id="lesson-one-student">
            <p><br>
                JS1
            </p>
            <p><br>
                FC-DEV2
            </p>
            <p><br>
                30/03/20
            </p>
            <p id="hour-begin-end">
                Heure début : 
                <input type="text" name="hour-begin" id="hour-begin" value="9H00"><br><br>
           
                Heure fin : 
                <input type="text" name="hour-end" id="hour-end" value="13H00">
            </p>
            <div>
                <div id="open-class">Ce cours est ouvert !</div>
            </div>
            <div>
            <button id="iampresent" type="submit">
                <a href="#">Je suis présent</a>
            </button>
            </div> 
            <div>
                <button id="justify-an-absence" type="submit">
                    <a href="#">Justifier une absence</a>
                </button>
            </div>
            <div>
                <button id="report-a-delay" type="submit">
                    <a href="#">Signaler un retard</a>
                </button>
            </div>  

        </div>

        <div id="lesson-two-student">
            <p><br>
                PHP
            </p>
            <p><br>
                FC-DEV2
            </p>
            <p><br>
                09/04/20
            </p>
            <p id="hour-begin-end">
                Heure début : 
                <input type="text" name="hour-begin" id="hour-begin" value="14H00"><br><br>
            
                Heure fin : 
                <input type="text" name="hour-end" id="hour-end" value="17H00">
            </p>
            <div>
                <div id="close-one-class">Ce cours n'est pas encore ouvert !</div>
            </div>
        </div>

        <div id="lesson-three-student">
            <p><br>
                HTML/CSS
            </p>
            <p><br>
                FC-DEV2
            </p>
            <p><br>
                15/03/20
            </p>
            <p id="hour-begin-end">
                Heure début : 
                <input type="text" name="hour-begin" id="hour-begin" value="9H00"><br><br>
            
                Heure fin : 
                <input type="text" name="hour-end" id="hour-end" value="13H00">
            </p>
            <div>
                <div id="close-two-class">Ce cours est terminé !</div>
            </div>  
        </div>
    </div>
    </section>

   
