
    <section id="top-section-header-and-title">
        <header>
            <img src="integrations/res/img/logo.png" alt="logo">
            <nav>
                <ul>
                    <li>
                        <button type="button">
                            <i class="fas fa-chalkboard-teacher"></i>
                            <a href="connexion.php" alt="" >Déconnexion</a>
                        </button>
                    </li>
                </ul>
            </nav>
        </header>
    </section>

    <div class="container-creer-classe">
    
        <div class="msg-creer-classe">
            <i class="far fa-user icon-user"></i>
            <h1>Créer une Classe</h1>
        </div>
        
        <?php if (!empty($ERRORS)) : ?>
            <div class="error">
                <ul>
                <?php foreach ($ERRORS as $error) : ?>
                    <li><?= $error; ?></li>
                <?php endforeach; ?>
                </ul>
            </div>
        <?php endif; ?>


        <form id="form-creeClasse" method="POST"  action="creerClasse.php" >
            <label for="name">Nom de la classe : </label>
            <input type="text" name="name" id="name" placeholder="Nom de la Classe" value="<?= isset($name) ? $name : ''; ?>"><br>
            <button class="button button-success" type="submit">Ajouter</button>
        </form>

        <section id="section-ajoutEtudiants-creer-classe">
            <label>Les étudiants déjà ajoutés à cette classe : </label>
            <ul>
                <?php foreach($utilisateurs as $utilisateur) : ?>
                    <li><?= $utilisateur['prenom']; ?> <?= $utilisateur['nom']; ?> <button class="button button-info">Modifier</button><button class="button button-danger">Supprimer</button></li>
                <?php endforeach; ?>
            </ul>
            
        </section>
        
    </div>
       
