
    <section id="top-section-header-and-title">
        <header>
            <img src="integrations/res/img/logo.png" alt="logo">
            <nav>
                <ul>
                    <li>
                        <button type="button">
                        <i class="fas fa-chalkboard-teacher"></i>
                        <a href="connexion.php" alt="" >Déconnexion</a>
                        </button>
                    </li>
                </ul>
            </nav>
        </header>
    </section>

    <section id="middle-section">

        <div class="title-message">
        <i class="far fa-user icon-user"></i>
        <h1>Ajouter un cours<br>
            "L'enseignement est l'une des clés de la réussite"</h1>
        </div>

        <?php if (!empty($ERRORS)) : ?>
            <div class="error">
                <ul>
                <?php foreach ($ERRORS as $error) : ?>
                    <li><?= $error; ?></li>
                <?php endforeach; ?>
                </ul>
            </div>
        <?php endif; ?>
    
        <form id="form" method="POST" action="ajouterCours.php">
            <p>
                <label>Nom du cours</label>
                <input type="text" placeholder="Nom du cours">
            </p>
            <p>
                <label>Classe associée à ce cours</label>
                <select>
                    <?php foreach($classes as $classe) : ?>
                    <option value="<?=$classes['idClasse'];?>"><?= $classe['nom']; ?>
                    </option>
                    <?php endforeach; ?>  
                </select>
            </p>

            <section id="date-cours">
                <p>
                    <label>Date de début du cours :</label><br>
                    <input type="date">
                    <input type="time" value="09:30">
                </p>
                <p>
                    <label>Date de fin du cours :</label><br>
                    <input type="date">
                    <input type="time" value="17:30">  
                </p>
            </section>
            <button class="button button-success" type="submit">Ajouter un cours</button>
        </form>
    </section>    

