
    <section id="top-section-header-and-title">
        <header>
            <img src="integrations/res/img/logo.png" alt="logo">
            <nav>
                <ul>
                    <li>
                        <button type="button">
                            <i class="fas fa-chalkboard-teacher"></i>
                            <a href="connexion.php" alt="" >Déconnexion</a>
                        </button>
                    </li>
                </ul>
            </nav>
        </header>
    </section>

    <section id="middle-section">
    
        <div class="title-message">
            <i class="far fa-user icon-user"></i>
            <h1>Créer une Classe<br>
            "L'enseignement est l'une des clés de la réussite"</h1>
        </div>
        
        <?php if (!empty($ERRORS)) : ?>
            <div class="error">
                <ul>
                <?php foreach ($ERRORS as $error) : ?>
                    <li><?= $error; ?></li>
                <?php endforeach; ?>
                </ul>
            </div>
        <?php endif; ?>


        <form id="form" method="POST"  action="creerNouvelleClasse.php" >
            <p>
                <label>Nom de la classe : </label>
                <input type="text" name="name" id="name" placeholder="Nom de la Classe" value="<?= isset($name) ? $name : ''; ?>">
            </p>
            <button class="button button-success" type="submit">Ajouter une classe</button>
        </form>

        
    </section>
       
