
    <section id="top-section-header-and-title">
        <header>
            <img src="integrations/res/img/logo.png" alt="logo">
            <nav>
                <ul>
                    <li>
                        <button type="button">
                        <i class="fas fa-chalkboard-teacher"></i>
                        <a href="connexion.php" alt="" >Déconnexion</a>
                        </button>
                    </li>
                </ul>
            </nav>
        </header>
    </section>

    <section id="middle-section">

        <div class="title-message">
        <i class="far fa-user icon-user"></i>
        <h1>Modifier un cours<br>
            "L'enseignement est l'une des clés de la réussite"</h1>
        </div>

        <?php if (!empty($ERRORS)) : ?>
            <div class="error">
                <ul>
                <?php foreach ($ERRORS as $error) : ?>
                    <li><?= $error; ?></li>
                <?php endforeach; ?>
                </ul>
            </div>
        <?php endif; ?>
    
        <form id="form" method="POST" action="modifierCour.php">
            
            <p>
                <label for="titre">Titre: </label>
                <input type="text" name="titre" id="titre" value="<?= isset($titre) ? $titre : $cour['titre']; ?>">
            </p>
            <p>
                <label for="dateDebut">Date de Début : </label>
                <input type="date" name="dateDebut" id="dateDebut" value="<?= isset($dateDebut) ? $dateDebut : $cour['dateDebut']; ?>">
                <input type="time" name="dateDebut" id="dateDebut" value="<?= isset($dateDebut) ? $dateDebut : $cour['nom']; ?>">
            </p>
            <p>
                <label for="dateFin">Date de fin : </label>
                <input type="date" name="dateFin" id="dateFin" value="<?= isset($dateFin) ? $dateFin : $cour['nom']; ?>">
                <input type="time" name="dateFin" id="dateFin" value="<?= isset($dateFin) ? $dateFin : $cour['nom']; ?>">
            </p>
            
            <p>
                <label>Classe associée à ce cours</label>
                <select>
                    <?php foreach($classes as $classe) : ?>
                    <option value="<?=$classes['idClasse'];?>"><?= $classe['nom']; ?>
                    </option>
                    <?php endforeach; ?>  
                </select>
            </p>
            <input type="hidden" name="idCours" value="<?= isset($idCour) ? $idCour : $cour['idCours']; ?>" />
            <button class="button button-info" type="submit">Modifier</button> 

            
        </form>
    </section>    

