
    <section id="top-section-header-and-title">
        <header>
            <img src="integrations/res/img/logo.png" alt="logo">
            <nav>
                <ul>
                    <li>
                        <button type="button">
                            <i class="fas fa-chalkboard-teacher"></i>
                            <a href="connexion.php" alt="" >Déconnexion</a>
                        </button>
                    </li>
                </ul>
            </nav>
        </header>
    </section>
    
    <section id="middle-section">
    
        <div class="title-message">
            <i class="far fa-user icon-user"></i>
            <h1>Modifier un Utilisateur<br>
            "L'enseignement est l'une des clés de la réussite"</h1>
        </div>

        <form id="form" method="POST" action="modifierUtilisateur.php">
            
            <p>
                <label for="name">Nom : </label>
                <input type="text" name="nom" id="name" value="<?= isset($name) ? $name : $utilisateur['nom']; ?>">
            </p>
            <p>
                <label for="firstname">Prénom : </label>
                <input type="text" name="prenom" id="firstname" value="<?= isset($firstname) ? $firstname : $utilisateur['prenom']; ?>">
            </p>
            <p>
                <label for="email">Email : </label>
                <input type="email" name="email" id="email" value="<?= isset($email) ? $email : $utilisateur['email']; ?>">
            </p>
            <p>
                <label for="password">Mot de passe : </label>
                <input type="password" name="motDePasse" id="enterpassword" value="<?= isset($enterpassword) ? $enterpassword : ''; ?>">
            </p>
            <p>
                <label>Rôle  : </label>
                <select name="role">
                    <option value="administrateur" <?= ($utilisateur['role'] === 'administrateur' ? 'selected' : ''); ?>>Administrateur</option>
                    <option value="etudiant" <?= ($utilisateur['role'] === 'etudiant' ? 'selected' : ''); ?>>Etudiant</option>
                    <option value="formateur" <?= ($utilisateur['role'] === 'formateur' ? 'selected' : ''); ?>>Formateur</option> 
                </select>
            </p>
            <p>
            <label>Classe  : </label>
                <select name="idClasse">
                    <option>N/A</option>
                    <?php foreach($classes as $classe) : ?>
                        <option <?= ($utilisateur['idClasse'] == $classe['idClasse'] ? 'selected' : ''); ?> value="<?=$classe['idClasse'];?>">
                            <?= $classe['nom']; ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </p>
            
            <button class="button button-info" type="submit">Modifier</button>
        </form>
    </section>
    
