
<section id="top-section-header-and-title">
    <header>
        <img src="integrations/res/img/logo.png" alt="logo">

        <nav>
            <ul>
                <li>
                    <button type="button">
                        <i class="fas fa-chalkboard-teacher"></i>
                    <a href="connexion.php">Connexion</a>
                    </button>
                </li>
                <li>
                    <button type="button">
                    <i class="far fa-address-card"></i>
                    <a href="inscription.php">Inscription</a> 
                    </button>
                </li>
            </ul>
        </nav>
    </header>
</section>

<section id="middle-section-home">
    <div>
        <h1>Bienvenue <?php echo $nom . ' ' . $prenom; ?> sur la page <br> d'accueil <br>
        <br> Help Yourself</h1>
    </div>
</section>