

    <section id="top-section-header-and-title">

        <header>
            <img src="integrations/res/img/logo.png" alt="logo">

            <nav>
                <ul>
                    <li>
                        <button type="button">
                        <i class="fas fa-chalkboard-teacher"></i>
                        <a href="index.php">Retour à l'accueil</a>
                        </button> 
                    </li>
                </ul>
            </nav>
        </header>
    </section>

    <section id="middle-section-registration">

        <div>
        <i class="far fa-user icon-user"></i>
        <h1>Bienvenue sur votre page d'inscription<br>
            "L'enseignement est l'une des clés de la réussite"</h1>
        </div>

        <form id="form-registration" method="POST" action="inscription.php">
            <p>
                <label for="name">Votre nom : </label>
                <input type="text" name="name" id="name" required>
            </p>
            <p>
                <label for="firstname">Votre prénom : </label>
                <input type="text" name="firstname" id="firstname" required>
            </p>
            <p>
                <label for="email">Votre email : </label>
                <input type="email" name="email" id="email" required>
            </p>
            <p>
                <label for="password">Votre mot de passe : </label>
                <input type="password" name="enterpassword" id="enterpassword" required>
            </p>
            <p>
                <label for="password">Confirmation : </label>
                <input type="password" name="confirmpassword" id="confirmpassword" required>
            </p>
            <div>
                <button id="button-registration" type="submit">
                    Inscription
                </button>
            </div>
        </form>

        
    </section>

