

    <section id="top-section-header-and-title">

        <header>
            <img src="integrations/res/img/logo.png" alt="logo">

            <nav>
                <ul>
                    <li>
                        <button type="button">
                        <i class="fas fa-chalkboard-teacher"></i>
                        <a href="index.php">Retour à l'accueil</a>
                        </button> 
                    </li>
                </ul>
            </nav>
        </header>
    </section>

    <section id="middle-section">

        <div class="title-message">
        <i class="far fa-user icon-user"></i>
        <h1>Bienvenue sur votre page d'inscription<br>
            "L'enseignement est l'une des clés de la réussite"</h1>
        </div>
    
        <?php if (!empty($ERRORS)) : ?>
            <div class="error">
                <ul>
                <?php foreach ($ERRORS as $error) : ?>
                    <li><?= $error; ?></li>
                <?php endforeach; ?>
                </ul>
            </div>
        <?php endif; ?>

        <form id="form" method="POST" action="inscription.php">
            <p>
                <label for="name">Votre nom : </label>
                <input type="text" name="name" id="name" value="<?= isset($name) ? $name : ''; ?>">
            </p>
            <p>
                <label for="firstname">Votre prénom : </label>
                <input type="text" name="firstname" id="firstname" value="<?= isset($firstname) ? $firstname : ''; ?>">
            </p>
            <p>
                <label for="email">Votre email : </label>
                <input type="email" name="email" id="email" value="<?= isset($email) ? $email : ''; ?>">
            </p>
            <p>
                <label for="password">Votre mot de passe : </label>
                <input type="password" name="enterpassword" id="enterpassword">
            </p>
            <p>
                <label for="password">Confirmation : </label>
                <input type="password" name="confirmpassword" id="confirmpassword">
            </p>
            <div>
                <button class="button button-success" type="submit">
                    Inscription
                </button>
            </div>
        </form>
    </section>
        
    

