
    <?php include 'integrations/part/navbar.part.php'; ?>
    
    <section id="middle-section">
    
        <div class="title-message">
            <i class="far fa-user icon-user"></i>
            <h1>Les Utilisateurs<br>
            "L'enseignement est l'une des clés de la réussite"</h1>
        </div>



    <form id="form-list-users" method="POST" action="listeDesUtilisateurs.php">
            <p>  
            <input type="text" placeholder="Entrer un nom">
            <button class="button button-success">Rechercher</button>
            </p>
                
                    
            
                

<table id="user_list">
  <tr>
    <th>Nom</th>
    <th>Prénom</th>
    <th>Email</th>
    <th>Role</th>
    <th>Classe</th>
    <th>Actions</th>
  </tr>
  <?php foreach($utilisateurs as $utilisateur) : ?>
  <tr>
    <td><?= $utilisateur['nom']; ?></td>
    <td><?= $utilisateur['prenom']; ?></td>
    <td><?= $utilisateur['email']; ?></td>
    <td><?= $utilisateur['role']; ?></td>
    <td><?= $utilisateur['idClasse']; ?></td>
    <td>
        <div class="user_list_btn">
        <a class="button button-info" href="formulaireUtilisateur.php?id=<?= $utilisateur['idUtilisateur']; ?>">Modifier</a>
        <a class="button button-danger" href="supprimerUtilisateur.php?id=<?= $utilisateur['idUtilisateur']; ?>">Supprimer</a>
        </div>
    </td>
  </tr>
  <?php endforeach; ?>
  
</table>
        </form>  
    </section>

<script>

    $(document).ready(function() {
        $('.button-danger').on('click', function(event){
            event.preventDefault();
            if(confirm('Voulez vous vraiment supprimer cet utilisateur ?') == true){
                window.location.href = $(this).attr('href');
            }
        });
    });



   /* $(document).ready(function() {
        $('.button-info').on('click', function(event){
            event.preventDefault();
            let id = $('#user_selected').val();
            window.location.href = "modifierUtilisateur.php?id="+id;
        });
    }); */
</script>
    