
    <section id="top-section-header-and-title">
        <header>
            <img src="integrations/res/img/logo.png" alt="logo">
            <nav>
                <ul>
                    <li>
                        <button type="button">
                            <i class="fas fa-chalkboard-teacher"></i>
                            <a href="connexion.php" alt="" >Déconnexion</a>
                        </button>
                    </li>
                </ul>
            </nav>
        </header>
    </section>
    <div class="container-liste-des-cours">
    
        <div class="msg-liste-des-cours">
            <i class="far fa-user icon-user"></i>
            <h1>Liste des Cours</h1>
        </div>

        <form id="form-liste-des-cours">
            <label>Classe :</label>
            <select name="" id="">
                <option value="">Fc Dev </option>
                <option value="">Chef de Projets</option>
                <option value="">Fc Ux</option>
                <option value="">Fc Motion Design</option>
            </select>

            <label>Date du cours :</label>
            <input type="date">
            <button class="button button-success">Rechercher un cours</button>
        </form>
        <section id="section-liste-des-cours">
            <label>La liste des cours :</label>
            <ul>
                <?php foreach($listedecours as $cours) : ?>
                    <li><?= $cours['titre']; ?>  <button class="button button-info">Modifier</button><button class="button button-danger">Supprimer</button></li>
                <?php endforeach; ?>
            </ul>
        </section>
    </div>

    