
    <section id="top-section-header-and-title">
        <header>
            <img src="integrations/res/img/logo.png" alt="logo">
            <nav>
                <ul>
                    <li>
                        <button type="button">
                            <i class="fas fa-chalkboard-teacher"></i>
                            <a href="connexion.php" alt="" >Déconnexion</a>
                        </button>
                    </li>
                </ul>
            </nav>
        </header>
    </section>
    
    <section id="middle-section">
    
        <div class="title-message">
            <i class="far fa-user icon-user"></i>
            <h1>Les Utilisateurs<br>
            "L'enseignement est l'une des clés de la réussite"</h1>
        </div>

        <form id="form" method="POST" action="listeDesUtilisateurs.php">
            <p>
                <select>
                    <option value="">Administrateur </option>
                    <option value="">Etudiant</option>
                    <option value="">Formateur</option> 
                </select>
                <select>
                    <option value="">Fc Dev </option>
                    <option value="">Chef de Projets</option>
                    <option value="">Fc Ux</option>
                    <option value="">Fc Motion Design</option>
                </select>
            </p>
            <p>  
            <input type="text" placeholder="Entrer un nom">
            <button class="button button-success">Rechercher</button>
            </p>
                
                    
            
                

                    <table id="user_list">
  <tr>
    <th>Nom</th>
    <th>Prénom</th>
    <th>Email</th>
    <th>Role</th>
    <th>Actions</th>
  </tr>
  <?php foreach($utilisateurs as $utilisateur) : ?>
  <tr>
    <td><?= $utilisateur['nom']; ?></td>
    <td><?= $utilisateur['prenom']; ?></td>
    <td><?= $utilisateur['email']; ?></td>
    <td><?= $utilisateur['role']; ?></td>
    <td>
        <div class="user_list_btn">
        <a class="button button-info" href="modifierUtilisateur.php?id=<?= $utilisateur['idUtilisateur']; ?>">Modifier</a>
        <a class="button button-danger" href="supprimerUtilisateur.php?id=<?= $utilisateur['idUtilisateur']; ?>">Supprimer</a>
        </div>
    </td>
  </tr>
  <?php endforeach; ?>
  
</table>
        </form>  
    </section>

<script>

    $(document).ready(function() {
        $('.button-danger').on('click', function(event){
            event.preventDefault();
            if(confirm('Voulez vous vraiment supprimer cet utilisateur ?') == true){
                window.location.href = $(this).attr('href');
            }
        });
    });



   /* $(document).ready(function() {
        $('.button-info').on('click', function(event){
            event.preventDefault();
            let id = $('#user_selected').val();
            window.location.href = "modifierUtilisateur.php?id="+id;
        });
    }); */
</script>
    