<?php include 'integrations/part/navbar.part.php'; ?>
    
    <section id="middle-section">
    
        <div class="title-message">
            <i class="far fa-user icon-user"></i>
            <h1>Liste des Cours<br>
            "L'enseignement est l'une des clés de la réussite"</h1>
        </div>

        <form id="form">
            <p>
                <label>Les sessions de cours planifiées :</label>
                <select>
                    <?php foreach($listedecours as $cours) : ?>
                    <option value="<?= $cours['titre']; ?>">(<?= $cours['etat']; ?>)</option>
                    <?php endforeach; ?>
                </select>
            </p>
            <p>
                <label>Classe :</label>
                <select>
                    <option value="">Fc Dev </option>
                    <option value="">Chef de Projets</option>
                    <option value="">Fc Ux</option>
                    <option value="">Fc Motion Design</option>
                </select>
            </p>
            <button class="button button-success" type="submit">Créer un nouveau cours</button>    
        </form>
        
</section>

    