
    <section id="top-section-header-and-title">
        <header>
            <img src="integrations/res/img/logo.png" alt="logo">
            <nav>
                <ul>
                    <li>
                        <button type="button">
                            <i class="fas fa-chalkboard-teacher"></i>
                            <a href="connexion.php" alt="" >Déconnexion</a>
                        </button>
                    </li>
                </ul>
            </nav>
        </header>
    </section>
    <div class="container-liste-des-classes">
    
        <div class="msg-liste-des-classes">
            <i class="far fa-user icon-user"></i>
            <h1>Liste des Classes</h1>
        </div>

        <form id="recherche-liste-des-classes">
            <label>Rechercher une classe :</label> 
            <input type="text" placeholder="Fc Dev">
            <button class="button button-success">Rechercher</button>
        </form>

        <section id="section-liste-des-classes">
            <label>La liste des classes :</label> 
            <ul>
            <?php foreach($classes as $classe) : ?>
                    <li><?= $classe['nom']; ?><button class="button button-info">Modifier</button><button class="button button-danger">Supprimer</button></li>
                <?php endforeach; ?>
            </ul>
        </section>
    </div>

