<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title><?= $PAGE['title']; ?> - Please Help Yourself</title>
    <link rel="stylesheet" href="<?php echo $HOST_URL; ?>integrations/css/style.css">
</head>
<body class="container">
    
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>


<!-- Inclusion du fichier de la page courante (renseigné dans le PHP juste avant d'inclure le MASTER.phtml) -->

<?php include   $PAGE['template']; ?>


<script src="integrations/lib/all.min.js"></script>

</body>
</html>