
    <section id="top-section-header-and-title">
        <header>
            <img src="integrations/res/img/logo.png" alt="logo">
            <nav>
                <ul>
                    <li>
                        <button type="button">
                            <i class="fas fa-chalkboard-teacher"></i>
                            <a href="connexion.php" alt="" >Déconnexion</a>
                        </button>
                    </li>
                </ul>
            </nav>
        </header>
    </section>
    
    <section id="middle-section">
    
        <div class="title-message">
            <i class="far fa-user icon-user"></i>
            <h1>Modifier une Classe<br>
            "L'enseignement est l'une des clés de la réussite"</h1>
        </div>

        <form id="form" method="POST"  action="modifierClasse.php" >
            <p>
                <label>Nom de la classe : </label>
                <input type="text" name="name" id="name" placeholder="Nom de la Classe" value="<?= isset($name) ? $name : ''; ?>">
            </p>
            <a class="button button-info" href="modifierClasse.php?id=<?= $classe['idClasse']; ?>">Modifier</a>
            <!--<button class="button button-success" type="submit">Modifier une classe</button>-->
        </form>
        
    </section>

    <script>
    $(document).ready(function() {
        $('.button-info').on('click', function(event){
            event.preventDefault();
            let id = $('#user_selected').val();
            window.location.href = "modifierClasse.php?id="+id;
        });
    });
    </script>

