
    <section id="top-section-header-and-title">
        <header>
            <img src="integrations/res/img/logo.png" alt="logo">
            <nav>
                <ul>
                    <li>
                        <button type="button">
                            <i class="fas fa-chalkboard-teacher"></i>
                            <a href="connexion.php" alt="" >Déconnexion</a>
                        </button>
                    </li>
                </ul>
            </nav>
        </header>
    </section>
    
    <div class="container-modifier-utilisateur">
    
        <div class="msg-modifier-utilisateur">
            <i class="far fa-user icon-user"></i>
            <h1>Modifier un Utilisateur</h1>
        </div>

        <p>L'utilisateur à modifier est :</p>
        <?php var_dump($utilisateur); ?>

        <form method="POST" action="modifierUtilisateur.php">
            <p>
            <select name="role">
                <option value="administrateur" <?= ($utilisateur['role'] === 'administrateur' ? 'selected' : ''); ?>>Administrateur</option>
                <option value="etudiant" <?= ($utilisateur['role'] === 'etudiant' ? 'selected' : ''); ?>>Etudiant</option>
                <option value="formateur" <?= ($utilisateur['role'] === 'formateur' ? 'selected' : ''); ?>>Formateur</option> 
            </select>
            <select name="class" id="">
                <option>N/A</option>
                <?php foreach($classes as $classe) : ?>
                    <option <?= ($utilisateur['idClasse'] == $classe['idClasse'] ? 'selected' : ''); ?> value="<?=$classe['idClasse'];?>">
                        <?= $classe['nom']; ?>
                    </option>
                <?php endforeach; ?>
            </select>
            </p>
            <p>
                <label for="name">Votre nom : </label>
                <input type="text" name="name" id="name" value="<?= isset($name) ? $name : $utilisateur['nom']; ?>">
            </p>
            <p>
                <label for="firstname">Votre prénom : </label>
                <input type="text" name="firstname" id="firstname" value="<?= isset($firstname) ? $firstname : $utilisateur['prenom']; ?>">
            </p>
            <p>
                <label for="email">Votre email : </label>
                <input type="email" name="email" id="email" value="<?= isset($email) ? $email : $utilisateur['email']; ?>">
            </p>
            <p>
                <label for="password">Votre mot de passe : </label>
                <input type="password" name="enterpassword" id="enterpassword" value="<?= isset($enterpassword) ? $enterpassword : ''; ?>">
            </p>
            <div>
            <button class="button button-info" type="submit">Modifier cet utilisateur</button>
        </form>
    </div>
    
