
    <section id="top-section-header-and-title">
        <header>
            <img src="integrations/res/img/logo.png" alt="logo">
            <nav>
                <ul>
                    <li>
                        <i class="fas fa-chalkboard-teacher"></i>
                        <a href="connexion.php" alt="" >Déconnexion</a>
                    </li>
                </ul>
            </nav>
        </header>
    </section>
    <h1 id="modifier-cours">Modifier un cours</h1>

    <hr>

    <form id="form-modifier-cours">
        <select>
            <option value="">Fc Dev </option>
            <option value="">Chef de Projets</option>
            <option value="">Fc Ux</option>
            <option value="">Fc Motion Design</option>
        </select>
        <input type="text" placeholder="Nom du cours">
        <button class="button button-success">Rechercher</button>
    </form>
    <section id="section-modifier-cours">
        <ul>
            <li>Cours de ReactJS (exemple) <button class="button button-info">Modifier</button></li>
            <li>Cours de HTML / CSS <button class="button button-info">Modifier</button></li>
            <li>Cours de JavaScript <button class="button button-info">Modifier</button></li>
            <li>Cours de PHP (Laravel) <button class="button button-info">Modifier</button></li>
            <li>Crée un site Web avec WordPress <button class="button button-info">Modifier</button></li>
            <li>Le Framework React <button class="button button-info">Modifier</button></li>
        </ul>
    </section>

