
    <section id="top-section-header-and-title">
        <header>
            <img src="integrations/res/img/logo.png" alt="logo">
            <nav>
                <ul>
                    <li>
                        <i class="fas fa-chalkboard-teacher"></i>
                        <a href="connexion.php" alt="" >Déconnexion</a>
                    </li>
                </ul>
            </nav>
        </header>
    </section>
    <h1 id="title-modifier-classe">Modifier une classe</h1>

    <button class="button button-info">Modifier la classe</button>

    <hr>

    <form id="form-modifier-classe">
        <div class="nom-modifier-classe">
            <label>Nom de la classe : </label>
            <input type="text" placeholder="Fc Dev">
        </div>
        <div class="ajout-etudiant-modifier-classe">
            <label>Ajout d'étudiants : </label>
            <input type="text" placeholder="Antoine La">
            <button class="button button-success">Rechercher</button>
        </div>
    </form>
    <section id="section-ajoutEtudiants-modifier-classe">
        <label>Les étudiants déjà ajoutés à cette classe : </label><br/>
        <ul>
            <li>Aurélien Durand <button class="button button-danger">Supprimer</button></li>
            <li>Céline Bernard <button class="button button-danger">Supprimer</button></li>
            <li>Alain Marechal <button class="button button-danger">Supprimer</button></li>
            <li>Laure Da Silva <button class="button button-danger">Supprimer</button></li>
            <li>Etienne Boucher <button class="button button-danger">Supprimer</button></li>
            <li>Magalie Perret <button class="button button-danger">Supprimer</button></li>
            <li>Christelle Monget <button class="button button-danger">Supprimer</button></li>
        </ul>
        
    </section>

