
    <section id="top-section-header-and-title">
        <header>
            <img src="integrations/res/img/logo.png" alt="logo">
            <nav>
                <ul>
                    <li>
                        <button type="button">
                            <i class="fas fa-chalkboard-teacher"></i>
                            <a href="connexion.php" alt="" >Déconnexion</a>
                        </button>
                    </li>
                </ul>
            </nav>
        </header>
    </section>
    
    <div class="container-modifier-classe">
    
        <div class="msg-modifier-classe">
            <i class="far fa-user icon-user"></i>
            <h1>Modifier une Classe</h1>
        </div>

        <form id="form-modifier-classe">
            <div class="nom-modifier-classe">
                <label>Nom de la classe : </label>
                <input type="text" placeholder="Fc Dev">
            </div>
            <div class="ajout-etudiant-modifier-classe">
                <label>Ajout d'étudiants : </label>
                <input type="text" placeholder="Antoine La">
                <button class="button button-success">Rechercher</button>
            </div>
        </form>

        <section id="section-ajout-etudiants-modifier-classe">
            <label>Les étudiants déjà ajoutés à cette classe : </label><br/>
            <ul>
                <li>Aurélien Durand <button class="button button-danger">Supprimer</button></li>
                <li>Céline Bernard <button class="button button-danger">Supprimer</button></li>
                <li>Alain Marechal <button class="button button-danger">Supprimer</button></li>
                <li>Laure Da Silva <button class="button button-danger">Supprimer</button></li>
                <li>Etienne Boucher <button class="button button-danger">Supprimer</button></li>
                <li>Magalie Perret <button class="button button-danger">Supprimer</button></li>
                <li>Christelle Monget <button class="button button-danger">Supprimer</button></li>
            </ul>
            
        </section>
        <div>
            <button class="button button-info" type="submit">Modifier la classe</button>
        </div>
    </div>

