
    <section id="top-section-header-and-title">
        <header>
            <img src="integrations/res/img/logo.png" alt="logo">
            <nav>
                <ul>
                    <li>
                        <button type="button">
                            <i class="fas fa-chalkboard-teacher"></i>
                            <a href="connexion.php" alt="" >Déconnexion</a>
                        </button>
                    </li>
                </ul>
            </nav>
        </header>
    </section>
    
    <div class="container-modifier-utilisateur">
    
        <div class="msg-modifier-utilisateur">
            <i class="far fa-user icon-user"></i>
            <h1>Modifier un Utilisateur</h1>
        </div>

        <form id="form-modifier-utilisateur">
            
            <select id="select-modifier-utilisateur">
                <option value="">Administrateur </option>
                <option value="">Etudiant</option>
                <option value="">Formateur</option> 
            </select>

            <label>Modifier un utilisateur : </label>
            <input type="text" placeholder="Antoine La">
            <button class="button button-success">Rechercher</button>

        </form>

        <section id="section-modifier-utilisateur">
            <label>Les utilisateurs déjà ajoutés : </label><br/>
            <ul>
                <li>Aurélien Durand <button class="button button-info">Modifier</button></li>
                <li>Céline Bernard <button class="button button-info">Modifier</button></li>
                <li>Alain Marechal <button class="button button-info">Modifier</button></li>
                <li>Laure Da Silva <button class="button button-info">Modifier</button></li>
                <li>Etienne Boucher <button class="button button-info">Modifier</button></li>
                <li>Magalie Perret <button class="button button-info">Modifier</button></li>
                <li>Christelle Monget <button class="button button-info">Modifier</button></li>
            </ul>    
        </section>

        <div class="ajout-user-btn">
            <button class="button button-info" type="submit">Modifier un utilisateur</button>
        </div>
    </div>
    
