

    <section id="top-section-header-and-title">

        <header>
            <img src="integrations/res/img/logo.png" alt="logo">

            <nav>
                <ul>
                    <li>
                        <button type="button">
                            <i class="fas fa-chalkboard-teacher"></i>
                            <a href="connexion.html">Déconnexion</a>
                        </button>
                    </li>
                </ul>
            </nav>
        </header>
    </section>

    <section id="middle-section">

        <div id="time-studies-students">
            <p>30/03/20 09:10:40</p>
        </div>

        <div class="title-message">
            <i class="far fa-user icon-user"></i>
            <h1>Relevé de présence du jour<br>
                "L'enseignement est l'une des clés de la réussite"
            </h1>
        </div>

        <div id="presence-students">
            <div>
                <select>
                    <?php foreach($cours as $cour) : ?>
                    <option value="<?= $cour['idCours']; ?>"><?= $cour['titre']; ?></option>
                    <?php endforeach; ?>
                </select>
                <p>
                    
                    <input type="date">
                    <input type="time" value="09:30">
                    <input type="time" value="17:30">
                </p>
                <select>
                    
                    <?php foreach($classes as $classe) : ?>
                    <option value="<?=$classes['idClasse'];?>"><?= $classe['nom']; ?></option>
                        </option>
                    <?php endforeach; ?>
                </select>
                
            </div>
        </div>

        <form id="form" method="POST" action="relevePresence.php">
           
            <table id="user_list">
            <tr>
                <th>Nom</th>
                <th>Prénom</th>
                <th>Status</th>
                <th>Actions</th>
            </tr>
            <?php foreach($utilisateurs as $utilisateur) : ?>
            <tr>
                <td><?= $utilisateur['nom']; ?></td>
                <td><?= $utilisateur['prenom']; ?></td>
                <td>
                    <select name="status">
                        <option value="present">Présent</option>
                        <option value="absent">Absent</option>
                        <option value="retard">Retard</option> 
                    </select></td>
                <td>
                    <button class="button button-success" type="submit">
                        <a href="#">Enregistrer</a>   
                    </button>
                </td>
            </tr>
            <?php endforeach; ?>
            
            </table>
            
        </form>     
    </section>





    