

    <section id="top-section-header-and-title">

        <header>
            <img src="integrations/res/img/logo.png" alt="logo">

            <nav>
                <ul>
                    <li>
                        <button type="button">
                            <i class="fas fa-chalkboard-teacher"></i>
                            <a href="connexion.html">Déconnexion</a>
                        </button>
                    </li>
                </ul>
            </nav>
        </header>
    </section>

    <section id="middle-section">

        <div id="time-studies-students">
            <p>30/03/20 09:10:40</p>
        </div>

        <div class="title-message">
            <i class="far fa-user icon-user"></i>
            <h1>Relevé de présence du jour<br>
                "L'enseignement est l'une des clés de la réussite"
            </h1>
        </div>

        <div id="presence-students">
            <div>
                <p>
                    Cours de JS1 en date du 30 mars 2020 <br><br>
                    Classe : FC - DEV2 <br><br>
                    9H00 - 13h00
                </p>
            </div>
        </div>

        <form id="form" method="POST" action="relevePresence.php">
            <p>
                <label>Entrer un nom : </label>   
                <input type="text">
            </p>
            <button class="button button-success">Rechercher</button>

            <p>
                <label>La liste des élèves :</label>
                <select>
                    <option>N/A</option>
                    <?php foreach($utilisateurs as $utilisateur) : ?>
                        <option value="<?=$utilisateur['idUtilisateur'];?>"><?= $utilisateur['nom']; ?> <?= $utilisateur['prenom']; ?></option>
                    <?php endforeach; ?>
                </select>

            </p>

            <div class="info-danger-btn">
                <div class="danger-btn">
                    <button class="button button-danger" type="submit"><a href="supprimerUtilisateur.php?id=<?= $utilisateur['idUtilisateur']; ?>">Absent</a></button>
                </div>
                <div class="info-btn">
                    <button class="button button-info" type="submit"><a href="modifierUtilisateur.php?id=<?= $utilisateur['idUtilisateur']; ?>">En retard</a></button>
                </div>
                <div class="success-btn">
                    <button class="button button-success" type="submit"><a href="modifierUtilisateur.php?id=<?= $utilisateur['idUtilisateur']; ?>">Présent</a></button>
                </div>     
            </div>
        
            <div>
                <button class="button button-success" type="submit">
                    <a href="#">Enregistrer</a>   
                </button>
            </div>
        </form>     
    </section>





    