
    <section id="top-section-header-and-title">
        <header>
            <img src="integrations/res/img/logo.png" alt="logo">
            <nav>
                <ul>
                    <li>
                        <button type="button">
                        <i class="fas fa-chalkboard-teacher"></i>
                        <a href="connexion.php" alt="" >Déconnexion</a>
                        </button>
                    </li>
                </ul>
            </nav>
        </header>
    </section>

    <section id="middle-section-delete-class">
    <div id="delete-class">
        <i class="far fa-user icon-user"></i>
        <h1>Bienvenue sur la page : <br> Supprimer une classe</h1>
        </div>
        
    <i class="fas fa-exclamation-triangle"></i>
    <p class="info-suppression"><span>Vous êtes sur le point de supprimer la classe "FC-DEV2".</span><br>
    Plusieurs cours sont associés à cette classe, <br> voulez-vous vraiment confirmer votre choix ?
    
    <button class="button button-danger">Supprimer</button>
    <button class="button button-info">Annuler</button></p>

    </section>

