
    <section id="top-section-header-and-title">
        <header>
            <img src="integrations/res/img/logo.png" alt="logo">
            <nav>
                <ul>
                    <li>
                        <i class="fas fa-chalkboard-teacher"></i>
                        <a href="connexion.php" alt="" >Déconnexion</a>
                    </li>
                </ul>
            </nav>
        </header>
    </section>
    
    <section id="middle-section-delete-studies">
    <div id="delete-studies">
        <i class="far fa-user icon-user"></i>
        <h1>Bienvenue sur la page : <br> Supprimer un cours</h1>
        </div>
    <i class="fas fa-exclamation-triangle"></i>
    <p class="info-suppression"><span>Vous êtes sur le point de supprimer le cours "HTML".</span><br>
    Êtes-vous sûr de vouloir supprimer ce cours ?

    <button class="button button-danger">Supprimer</button>
    <button class="button button-info">Annuler</button>
    </p>

    </section>

