
    <section id="top-section-header-and-title">
        <header>
            <img src="integrations/res/img/logo.png" alt="logo">
            <nav>
                <ul>
                    <li>
                        <i class="fas fa-chalkboard-teacher"></i>
                        <a href="connexion.php" alt="" >Déconnexion</a>
                    </li>
                </ul>
            </nav>
        </header>
    </section>
        
    <h1 id="supprimer-classe">Supprimer une classe</h1>

    <hr>

    <p class="info-suppression"><span>Vous êtes sur le point de supprimer la classe "HTML / CSS".</span><br>
    Plusieurs cours sont associés à cette classe , vous voulez vraiment confirmer votre choix ?</p>
    <button class="button button-info">Annuler</button>
    <button class="button button-danger">Supprimer</button>

