
    <section id="top-section-header-and-title">
        <header>
            <img src="integrations/res/img/logo.png" alt="logo">
            <nav>
                <ul>
                    <li>
                        <i class="fas fa-chalkboard-teacher"></i>
                        <a href="connexion.php" alt="" >Déconnexion</a>
                    </li>
                </ul>
            </nav>
        </header>
    </section>
    <h1 id="supprimer-cours">Supprimer un cours</h1>

    <hr>

    <p class="info-suppression">Etes vous sûre de vouloir supprimer ce cours ?</p>
    <button class="button button-info">Annuler</button>
    <button class="button button-danger">Supprimer</button>

