
    <section id="top-section-header-and-title">
        <header>
            <img src="integrations/res/img/logo.png" alt="logo">
            <nav>
                <ul>
                    <li>
                        <button type="button">
                            <i class="fas fa-chalkboard-teacher"></i>
                            <a href="connexion.php" alt="" >Déconnexion</a>
                        </button>
                    </li>
                </ul>
            </nav>
        </header>
    </section>
    
    <div class="container-utilisateurs">
    
        <div class="msg-utilisateurs">
            <i class="far fa-user icon-user"></i>
            <h1>Les Utilisateurs</h1>
        </div>

        <form id="form-utilisateurs">
            <label>Filtrer les résultats de la liste :</label><br>
            <select>
                <option value="">Administrateur </option>
                <option value="">Etudiant</option>
                <option value="">Formateur</option> 
            </select>
            <select>
                <option value="">Fc Dev </option>
                <option value="">Chef de Projets</option>
                <option value="">Fc Ux</option>
                <option value="">Fc Motion Design</option>
            </select>
            <input type="text" placeholder="Entrer un nom">
            <button class="button button-success">Rechercher</button>
        </form>
        <section id="section-liste-utilisateurs">
            <label>La liste des utilisateurs :</label>
            <ul>
                <?php foreach($utilisateurs as $utilisateur) : ?>
                    <li><?= $utilisateur['prenom']; ?> <?= $utilisateur['nom']; ?> <button class="button button-info">Modifier</button><button class="button button-danger">Supprimer</button></li>
                <?php endforeach; ?>
            </ul>
        </section>
        
    </div>

