<?php include '../integrations/part/navbar.etudiant.php'; ?>


    <section id="middle-section">

        <div class="title-message">
            <i class="far fa-user icon-user"></i>
            <h1>Bienvenue sur votre page d'accueil étudiant<br>
                "L'apprentissage est l'une des clés de la réussite"
            </h1>
        </div>

        <form id="form-list" method="POST" action="relevePresence.php">
            
            <table id="user_list">
                <tr>
                    <th>Titre</th>
                    <th>Classe</th>
                    <th>Date de Début</th>
                    <th>Date de Fin</th>
                    <th>Actions</th>
                </tr>

                <?php foreach($cours as $cour) : ?>
                        
                <tr>
                    <td><?= $cour['titre']; ?></td>
                    <td><?= $classes[$cour['idClasse']]; ?></td>
                    <td><?= strftime("%d %b %Y à %H:%M",strtotime($cour['dateDebut'])); ?></td>
                    <td><?= strftime("%d %b %Y à %H:%M",strtotime($cour['dateFin'])); ?></td>
                    <td>
                    <select name="status">
                        <option value="present">Présent</option>
                        <option value="absent">Absent</option>
                        <option value="retard">Retard</option> 
                    </select>
                    </td>
                </tr>
                <?php endforeach; ?>
            </table>
        </form>
    </section>

