

    <section id="top-section-header-and-title">

        <header>
            <img src="../integrations/res/img/logo.png" alt="logo">

            <nav>
                <ul>
                    <li>
                        <button type="button">
                            <i class="fas fa-chalkboard-teacher"></i>
                            <a href="connexion.php">Déconnexion</a>
                        </button>
                    </li>
                </ul>
            </nav>
        </header>
    </section>

    <section id="middle-section">

        <div id="time-studies-students">
            <p>30/03/20 09:03:23</p>
        </div>

        <div class="title-message">
            <i class="far fa-user icon-user"></i>
            <h1>Bienvenue sur votre page d'accueil étudiant<br>
                "L'apprentissage est l'une des clés de la réussite"
            </h1>
        </div>

        <div id="lessons-list">
            <div id="lesson-one">
                <p><br>
                    JS1
                </p>
                <p><br>
                    FC-DEV2
                </p>
                <p><br>
                    30/03/20
                </p>
                <p id="hour-begin-end">
                    Heure début : 
                    <input type="text" name="hour-begin" id="hour-begin" value="9H00"><br><br>
            
                    Heure fin : 
                    <input type="text" name="hour-end" id="hour-end" value="12H00">
                </p>
                <div>
                    <div id="message-open-close-lesson">Ce cours est ouvert !</div>
                </div>
                <div class="three-btn">
                    <div>
                    <button id="iampresent" type="submit">
                        <a href="#">Je suis présent</a>
                    </button>
                    </div> 
                    <div>
                        <button id="justify-an-absence" type="submit">
                            <a href="#">Justifier une absence</a>
                        </button>
                    </div>
                    <div>
                        <button id="report-a-delay" type="submit">
                            <a href="#">Signaler un retard</a>
                        </button>
                    </div> 
                </div> 

            </div>

            <div id="lesson-two">
                <p><br>
                    PHP
                </p>
                <p><br>
                    FC-DEV2
                </p>
                <p><br>
                    30/03/20
                </p>
                <p id="hour-begin-end">
                    Heure début : 
                    <input type="text" name="hour-begin" id="hour-begin" value="13H00"><br><br>
                
                    Heure fin : 
                    <input type="text" name="hour-end" id="hour-end" value="16H00">
                </p>
                <div>
                    <div id="message-open-close-lesson">Ce cours n'est pas encore ouvert !</div>
                </div>
            </div>

            <div id="lesson-three">
                <p><br>
                    HTML/CSS
                </p>
                <p><br>
                    FC-DEV2
                </p>
                <p><br>
                    30/03/20
                </p>
                <p id="hour-begin-end">
                    Heure début : 
                    <input type="text" name="hour-begin" id="hour-begin" value="16H30"><br><br>
                
                    Heure fin : 
                    <input type="text" name="hour-end" id="hour-end" value="19H30">
                </p>
                <div>
                    <div id="message-open-close-lesson">Ce cours est terminé !</div>
                </div>  
            </div>
        </div>

    </section>

   
