<?php include '../integrations/part/navbar.accueil.php'; ?>

<section id="middle-section">

    <div class="title-message">
    <i class="far fa-user icon-user"></i>
    <h1>Bienvenue sur votre page de connexion<br>
        "L'apprentissage est l'une des clés de la réussite"</h1>
    </div>

    <?php if (!empty($ERRORS)) : ?>
            <div class="error">
                <ul>
                <?php foreach ($ERRORS as $error) : ?>
                    <li><?= $error; ?></li>
                <?php endforeach; ?>
                </ul>
            </div>
        <?php endif; ?>

    <form id="form-connexion" action="connexion.php">
        
            <input type="email" id="email" placeholder="Email" required autofocus>
        
        
            <input type="password" id="motdepasse" placeholder="Mot de passe" required>
        
        <div>
        <button class="button button-success" type="submit">Connexion</button>
        </div>
    </form>

    
</section>
