<?php include '../integrations/part/navbar.accueil.php'; ?>


    <section id="middle-section">

        <div class="title-message">
        <i class="far fa-user icon-user"></i>
        <h1>Bienvenue sur votre page d'inscription<br>
            "L'enseignement est l'une des clés de la réussite"</h1>
        </div>
    
        <?php if (!empty($ERRORS)) : ?>
            <div class="error">
                <ul>
                <?php foreach ($ERRORS as $error) : ?>
                    <li><?= $error; ?></li>
                <?php endforeach; ?>
                </ul>
            </div>
        <?php endif; ?>

        <form id="form-inscription" method="POST" action="inscription.php">
            <div class="form-inscription-one">
                <p>
                    <input type="text" name="name" id="name" placeholder="Taper votre nom" value="<?= isset($name) ? $name : ''; ?>">
                </p>
                <p>
                    <input type="text" name="firstname" id="firstname" placeholder="Taper votre prénom" value="<?= isset($firstname) ? $firstname : ''; ?>">
                </p>
                <p>
                    <input type="email" name="email" id="email" placeholder="Taper votre Email" value="<?= isset($email) ? $email : ''; ?>">
                </p>
            </div>
            <div class="form-inscription-two">
                <p>   
                <input type="password" name="enterpassword" id="enterpassword" placeholder="Taper votre mot de passe" >
                </p>
                <p>
                    <input type="password" name="confirmpassword" id="confirmpassword" placeholder="Confirmer votre mot de passe" >
                </p>
            </div>
            <div>
                <button class="button button-success" type="submit">
                    Inscription
                </button>
            </div>
        </form>
    </section>
        
    

