<?php include '../integrations/part/navbar.accueil.php'; ?>


    <section id="middle-section">

        <div class="title-message">
        <i class="far fa-user icon-user"></i>
        <h1>Bienvenue sur votre page d'inscription<br>
            "L'enseignement est l'une des clés de la réussite"</h1>
        </div>
    
        <?php if (!empty($ERRORS)) : ?>
            <div class="error">
                <ul>
                <?php foreach ($ERRORS as $error) : ?>
                    <li><?= $error; ?></li>
                <?php endforeach; ?>
                </ul>
            </div>
        <?php endif; ?>

        <form id="form-inscription" method="POST" action="inscription.php">
            <div class="form-inscription-one">
                
                    <input type="text" name="name" id="name" placeholder="Nom" value="<?= isset($name) ? $name : ''; ?>"autofocus>
                
                    <input type="text" name="firstname" id="firstname" placeholder="Prénom" value="<?= isset($firstname) ? $firstname : ''; ?>">
                
                    <input type="email" name="email" id="email" placeholder="Email" value="<?= isset($email) ? $email : ''; ?>">
                
            </div>
            <div class="form-inscription-two">
                  
                <input type="password" name="motDePasse" id="motDePasse" placeholder="Mot de passe" >

                    <input type="password" name="confirmpassword" id="confirmpassword" placeholder="Confirmer votre mot de passe" >
 
                    <button class="button button-success" type="submit">
                        Inscription
                    </button>
                
            </div>
        </form>
    </section>
        
    

