<?php include '../integrations/part/navbar.part.php'; ?>
    
    <section id="middle-section">
    
        <div class="title-message">
            <i class="far fa-user icon-user"></i>
            <h1>Modifier une Classe<br>
            "L'enseignement est l'une des clés de la réussite"</h1>
        </div>

        <form id="form-inscription" method="POST"  action="modifierClasse.php" >
            <div class="form-ajout-classe">
                <p>
                    
                    <input type="text" name="nom" id="name" placeholder="Nom de la classe" value="<?= isset($name) ? $name : $classe['nom']; ?>"autofocus>
                </p>
                <input type="hidden" name="idClasse" value="<?= isset($idClasse) ? $idClasse : $classe['idClasse']; ?>" />
                <button class="button button-success" type="submit">Modifier</button>
            </div>
        </form>
        
    </section>
