<?php include '../integrations/part/navbar.part.php'; ?>
    
    <section id="middle-section">
    
        <div class="title-message">
            <i class="far fa-user icon-user"></i>
            <h1>Créer une nouvelle classe<br>
            "L'enseignement est l'une des clés de la réussite"</h1>
        </div>

        <?php if (!empty($ERRORS)) : ?>
            <div class="error">
                <ul>
                <?php foreach ($ERRORS as $error) : ?>
                    <li><?= $error; ?></li>
                <?php endforeach; ?>
                </ul>
            </div>
        <?php endif; ?>

        <form id="form-inscription" method="POST"  action="formulaireAjoutClasse.php" >
            <div class="form-ajout-classe">
                <p>
                    <input type="text" name="nom" id="name" placeholder="Nom de la classe" value="<?= isset($name) ? $name : ''; ?>" autofocus>
                </p>
                <input type="hidden" name="idClasse" value="<?= isset($idClasse) ? $idClasse : $classe['idClasse']; ?>" />
                <button class="button button-info" type="submit">Enregistrer</button>
            </div>
        </form>
        
    </section>
