<?php include '../integrations/part/navbar.part.php'; ?>
    
    <section id="middle-section">
    
        <div class="title-message">
            <i class="far fa-user icon-user"></i>
            <h1>Créer une nouvelle classe<br>
            "L'enseignement est l'une des clés de la réussite"</h1>
        </div>

        <?php if (!empty($ERRORS)) : ?>
            <div class="error">
                <ul>
                <?php foreach ($ERRORS as $error) : ?>
                    <li><?= $error; ?></li>
                <?php endforeach; ?>
                </ul>
            </div>
        <?php endif; ?>

        <form id="form" method="POST"  action="formulaireAjoutClasse.php" >
            <p>
                <label for="name">Nom de la classe : </label>
                <input type="text" name="nom" id="name" value="<?= isset($name) ? $name : ''; ?>">
            </p>
            <input type="hidden" name="idClasse" value="<?= isset($idClasse) ? $idClasse : $classe['idClasse']; ?>" />
            <button class="button button-info" type="submit">Enregistrer</button>
        </form>
        
    </section>
