<?php include '../integrations/part/navbar.part.php'; ?>
    
    <section id="middle-section">
    
        <div class="title-message">
            <i class="far fa-user icon-user"></i>
            <h1>Modifier une Classe<br>
            "L'enseignement est l'une des clés de la réussite"</h1>
        </div>

        <form id="form" method="POST"  action="modifierClasse.php" >
            <p>
                <label for="name">Nom de la classe : </label>
                <input type="text" name="nom" id="name" value="<?= isset($name) ? $name : $classe['nom']; ?>">
            </p>
            <input type="hidden" name="idClasse" value="<?= isset($idClasse) ? $idClasse : $classe['idClasse']; ?>" />
            <button class="button button-info" type="submit">Modifier</button>
        </form>
        
    </section>
