<?php include '../integrations/part/navbar.part.php'; ?>

<section id="middle-section">

    <div class="title-message">
        <i class="far fa-user icon-user"></i>
        <h1>Liste des Classes<br>
            "L'enseignement est l'une des clés de la réussite"</h1>
    </div>

    <div id="add-btn">
                    <a class="button button-info" href="formulaireAjoutClasse.php">Ajouter</a>
                </div>

    <form id="form-list" method="POST" action="listeDesClasses.php">

        <table id="user_list">
            <tr>
                <th>Classes</th>
                <th>Actions</th>
            </tr>
            <?php foreach ($classes as $classe) : ?>
                <tr>
                    <td><?= $classe['nom']; ?></td>
                    <td>
                        <div class="user_list_btn">
                            <a class="button button-info" href="formulaireClasse.php?id=<?= $classe['idClasse']; ?>">Modifier</a>
                            <a class="button button-danger" href="supprimerClasse.php?id=<?= $classe['idClasse']; ?>">Supprimer</a>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>

        </table>

    </form>
    
</section>

<script>

    $(document).ready(function() {
        $('.button-danger').on('click', function(event){
            event.preventDefault();
            if(confirm('Voulez vous vraiment supprimer cet utilisateur ?') == true){
                window.location.href = $(this).attr('href');
            }
        });
    });
</script>
