<?php include '../integrations/part/navbar.formateur.php'; ?>


    <section id="middle-section">

        <div class="title-message">
            <i class="far fa-user icon-user"></i>
            <h1>Bienvenue sur la page de vos cours<br>
                "L'enseignement est l'une des clés de la réussite"
            </h1>
        </div>

        <form id="form-list" method="POST" action="relevePresence.php">
            <p id="search-btn">  
            <input type="text" placeholder="Entrer un nom">
            <button class="button button-success">Rechercher</button>
            </p>

            <table id="user_list">
                <tr>
                    <th>Titre</th>
                    <th>Classe</th>
                    <th>Date de Début</th>
                    <th>Date de Fin</th>
                    <th>Actions</th>
                </tr>
                        <?php foreach($cours as $cour) : ?>
                        
                <tr>
                
                    <td><?= $cour['titre']; ?></td>
                    <td><?= $classes[$cour['idClasse']]; ?></td>
                    <td><?= strftime("%d %b %Y à %H:%M",strtotime($cour['dateDebut'])); ?></td>
                    <td><?= strftime("%d %b %Y à %H:%M",strtotime($cour['dateFin'])); ?></td>
                    
                    <td>
                    <div class="user_list_btn">
                        <input type="hidden" name="idClasse" value="<?= isset($idClasse) ? $idClasse : $classe['idClasse']; ?>" />
                        <button class="button button-info" type="submit">Ouvrir</button>

                        <input type="hidden" name="idClasse" value="<?= isset($idClasse) ? $idClasse : $classe['idClasse']; ?>" />
                        <button class="button button-danger" type="submit">Accéder</button>
                    </div>
                    
                    </td>
                </tr>
                <?php endforeach; ?>
                
                
            </table>
        </form>
    </section>

