<?php include '../integrations/part/navbar.formateur.php'; ?>


    <section id="middle-section">

        <div class="title-message">
            <i class="far fa-user icon-user"></i>
            <h1>Relevé de présence du jour<br>
                "L'enseignement est l'une des clés de la réussite"
            </h1>
        </div>

        <div id="add-btn">
            <a class="button button-info" href="#">Enregistrer</a>
        </div>
           
        <form id="form-list-cours" method="POST" action="relevePresence.php">
           
            <table id="user_list">
            <tr>
                <th>Nom</th>
                <th>Prénom</th>
                <th>Classe</th>
                <th>Status</th>
                
            </tr>
            <?php foreach($utilisateurs as $utilisateur) : ?>
            <tr>
                <td><?= $utilisateur['nom']; ?></td>
                <td><?= $utilisateur['prenom']; ?></td>
                <td><?= $utilisateur['idClasse']; ?></td>

                <td>
                    <select name="status">
                        <option value="present">Présent</option>
                        <option value="absent">Absent</option>
                        <option value="retard">Retard</option> 
                    </select></td>
                
            </tr>
            <?php endforeach; ?>
            
            </table>
            
        </form>
    
    </section>





    