
    <section id="top-section-header-and-title">
        <header>
            <img src="integrations/res/img/logo.png" alt="logo">
            <nav>
                <ul>
                    <li>
                        <button type="button">
                            <i class="fas fa-chalkboard-teacher"></i>
                            <a href="connexion.php" alt="" >Déconnexion</a>
                        </button>
                    </li>
                </ul>
            </nav>
        </header>
    </section>
    
    <section id="middle-section">
        
        <div class="title-message">
            <i class="far fa-user icon-user"></i>
            <h1>Créer un nouvel utilisateur<br>
            "L'enseignement est l'une des clés de la réussite"</h1>
        </div>

        <?php if (!empty($ERRORS)) : ?>
            <div class="error">
                <ul>
                <?php foreach ($ERRORS as $error) : ?>
                    <li><?= $error; ?></li>
                <?php endforeach; ?>
                </ul>
            </div>
        <?php endif; ?>
        
        <form id="form" method="POST" action="ajoutUtilisateur.php">
            <p>
                <select name="role">
                    <option value="administrateur">Administrateur</option>
                    <option value="etudiant">Etudiant</option>
                    <option value="formateur">Formateur</option> 
                </select>
                <select name="class" id="">
                    <option>N/A</option>
                <?php foreach($classes as $classe) : ?>
                        <option value="<?=$classe['idClasse'];?>"><?= $classe['nom']; ?></option>
                    <?php endforeach; ?>
                </select>
            </p>
            <p>
                <label for="name">Votre nom : </label>
                <input type="text" name="name" id="name" value="<?= isset($name) ? $name : ''; ?>">
            </p>
            <p>
                <label for="firstname">Votre prénom : </label>
                <input type="text" name="firstname" id="firstname" value="<?= isset($firstname) ? $firstname : ''; ?>">
            </p>
            <p>
                <label for="email">Votre email : </label>
                <input type="email" name="email" id="email" value="<?= isset($email) ? $email : ''; ?>">
            </p>
            <p>
                <label for="password">Votre mot de passe : </label>
                <input type="password" name="enterpassword" id="enterpassword" value="<?= isset($enterpassword) ? $enterpassword : ''; ?>">
            </p>
            <button class="button button-success" type="submit">Créer un nouvel utilisateur</button>
        </form>
</section>
