<?php include '../integrations/part/navbar.part.php'; ?>
    
    <section id="middle-section">
        
        <div class="title-message">
            <i class="far fa-user icon-user"></i>
            <h1>Créer un nouvel utilisateur<br>
            "L'enseignement est l'une des clés de la réussite"</h1>
        </div>

        <?php if (!empty($ERRORS)) : ?>
            <div class="error">
                <ul>
                <?php foreach ($ERRORS as $error) : ?>
                    <li><?= $error; ?></li>
                <?php endforeach; ?>
                </ul>
            </div>
        <?php endif; ?>
        
        <form id="form-inscription" method="POST" action="formulaireAjoutUtilisateur.php">

            <div class="form-inscription-one">
                    <input type="text" name="name" id="name" placeholder="Taper le nom" value="<?= isset($name) ? $name : ''; ?>" autofocus >
                
                    <input type="text" name="firstname" id="firstname" placeholder="Taper le prénom" value="<?= isset($firstname) ? $firstname : ''; ?>">
                
                    <input type="email" name="email" id="email" placeholder="Taper l'email" value="<?= isset($email) ? $email : ''; ?>">
                
                    <input type="password" name="enterpassword" id="enterpassword" placeholder="taper le mot de passe" value="<?= isset($enterpassword) ? $enterpassword : ''; ?>">
                
            </div>
            <div class="form-inscription-two">
                <select name="role">
                    <option value="administrateur">Administrateur</option>
                    <option value="etudiant">Etudiant</option>
                    <option value="formateur">Formateur</option> 
                </select>

                <select name="class">
                    <option>N/A</option>
                <?php foreach($classes as $classe) : ?>
                        <option value="<?=$classe['idClasse'];?>"><?= $classe['nom']; ?></option>
                    <?php endforeach; ?>
                </select>
                
                <input type="hidden" name="idUtilisateur" value="<?= isset($idUtilisateur) ? $idUtilisateur : $utilisateur['idUtilisateur']; ?>" />
                <button class="button button-success" type="submit">Enregistrer</button>

            </div>
        </form>
</section>
