<?php include '../integrations/part/navbar.part.php'; ?>
    
    <section id="middle-section">
        
        <div class="title-message">
            <i class="far fa-user icon-user"></i>
            <h1>Créer un nouvel utilisateur<br>
            "L'enseignement est l'une des clés de la réussite"</h1>
        </div>

        <?php if (!empty($ERRORS)) : ?>
            <div class="error">
                <ul>
                <?php foreach ($ERRORS as $error) : ?>
                    <li><?= $error; ?></li>
                <?php endforeach; ?>
                </ul>
            </div>
        <?php endif; ?>
        
        <form id="form" method="POST" action="formulaireAjoutUtilisateur.php">
            <p>
                <select name="role">
                    <option value="administrateur">Administrateur</option>
                    <option value="etudiant">Etudiant</option>
                    <option value="formateur">Formateur</option> 
                </select>
                <select name="class" id="">
                    <option>N/A</option>
                <?php foreach($classes as $classe) : ?>
                        <option value="<?=$classe['idClasse'];?>"><?= $classe['nom']; ?></option>
                    <?php endforeach; ?>
                </select>
            </p>
            <p>
                <label for="name">Votre nom : </label>
                <input type="text" name="name" id="name" value="<?= isset($name) ? $name : ''; ?>">
            </p>
            <p>
                <label for="firstname">Votre prénom : </label>
                <input type="text" name="firstname" id="firstname" value="<?= isset($firstname) ? $firstname : ''; ?>">
            </p>
            <p>
                <label for="email">Votre email : </label>
                <input type="email" name="email" id="email" value="<?= isset($email) ? $email : ''; ?>">
            </p>
            <p>
                <label for="password">Votre mot de passe : </label>
                <input type="password" name="enterpassword" id="enterpassword" value="<?= isset($enterpassword) ? $enterpassword : ''; ?>">
            </p>
            <input type="hidden" name="idUtilisateur" value="<?= isset($idUtilisateur) ? $idUtilisateur : $utilisateur['idUtilisateur']; ?>" />
            <button class="button button-success" type="submit">Enregistrer</button>
        </form>
</section>
