<?php include '../integrations/part/navbar.part.php'; ?>
    
    <section id="middle-section">
    
        <div class="title-message">
            <i class="far fa-user icon-user"></i>
            <h1>Modifier un Utilisateur<br>
            "L'enseignement est l'une des clés de la réussite"</h1>
        </div>

        <form id="form-inscription" method="POST" action="modifierUtilisateur.php">

            <div class="form-inscription-one">
                    <input type="text" name="nom" id="name" value="<?= isset($name) ? $name : $utilisateur['nom']; ?>"autofocus>

                    <input type="text" name="prenom" id="firstname" value="<?= isset($firstname) ? $firstname : $utilisateur['prenom']; ?>">
                
                    <input type="email" name="email" id="email" value="<?= isset($email) ? $email : $utilisateur['email']; ?>">
                
                    <input type="password" name="motDePasse" id="motDePasse" placeholder="Entrer votre mot de passe" value="<?= isset($password) ? $password : ''; ?>">
                
                </div>
            <div class="form-inscription-two">
                    <select name="role">
                        <option value="administrateur" <?= ($utilisateur['role'] === 'administrateur' ? 'selected' : ''); ?>>Administrateur</option>
                        <option value="etudiant" <?= ($utilisateur['role'] === 'etudiant' ? 'selected' : ''); ?>>Etudiant</option>
                        <option value="formateur" <?= ($utilisateur['role'] === 'formateur' ? 'selected' : ''); ?>>Formateur</option> 
                    </select>
                
                    <select name="idClasse">
                        <?php foreach($classes as $classe) : ?>
                            <option <?= ($utilisateur['idClasse'] == $classe['idClasse'] ? 'selected' : ''); ?> value="<?=$classe['idClasse'];?>">
                                <?= $classe['nom']; ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                
                <input type="hidden" name="idUtilisateur" value="<?= isset($idUtilisateur) ? $idUtilisateur : $utilisateur['idUtilisateur']; ?>" />
                <button class="button button-info" type="submit">Modifier</button>
            </div>
        </form>
    </section>
    
